# Generated by Django 6.1 on 2026-08-24 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPreferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricoes', models.CharField(max_length=100)),
                ('preferidos', models.CharField(max_length=100)),
                ('rejeitados', models.CharField(max_length=100)),
                ('fk_id_usuario', models.ForeignKey(db_column='fk_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='anamnese.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=15, unique=True)),
                ('quantidade', models.IntegerField()),
                ('fk_id_usuario', models.ForeignKey(db_column='fk_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='anamnese.usuarios')),
            ],
        ),
    ]
