# Generated by Django 6.1 on 2026-08-29 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuariopreferencias',
            name='fk_id_usuario',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='idade',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.JSONField(default=list)),
                ('estilo_alimentar', models.CharField(max_length=30)),
                ('alimentos_bons', models.JSONField(default=list)),
                ('alimentos_ruins', models.JSONField(default=list)),
                ('comobirdades', models.JSONField(default=list)),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anamnese.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='NotasFiscais',
            fields=[
                ('chave_acesso', models.IntegerField(primary_key=True, serialize=False)),
                ('data_compra', models.DateTimeField()),
                ('valor_total', models.FloatField()),
                ('cnpj', models.IntegerField()),
                ('metodo_pag', models.CharField(max_length=20)),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anamnese.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutosNotasFiscais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un', models.FloatField()),
                ('valor_unitario', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anamnese.categorias')),
                ('nota_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anamnese.notasfiscais')),
            ],
        ),
        migrations.DeleteModel(
            name='Alimentos',
        ),
        migrations.DeleteModel(
            name='UsuarioPreferencias',
        ),
    ]
